import type { Metadata } from "next";
import "@/css/globals.css";
import "@fontsource/inter/100.css";
import "@fontsource/inter/200.css";
import "@fontsource/inter/300.css";
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "@fontsource/inter/700.css";
import "@fontsource/inter/800.css";
import "@fontsource/inter/900.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextTopLoader from "nextjs-toploader";
import MobileNav from "@/components/MobileNav";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Otowa AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <NextTopLoader color="#6d67fe" showSpinner={false} />
        <Navbar />
        <Suspense fallback={null}>
          <MobileNav />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
