import type { Metadata } from "next";
import "@/css/globals.css";
import Navbar from "@/components/Navbar";


export const metadata: Metadata = {
  title: "Otowa AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
